"""added field comment

Revision ID: 77391234f51d
Revises: 3c11c3404d44
Create Date: 2025-12-31 22:49:41.338290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77391234f51d'
down_revision = '3c11c3404d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
