apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/elyes5/dda_saddem_elyes_projet_info3:latest
          ports:
            - containerPort: 5000
          # 1. On monte le fichier ici
          volumeMounts:
            - name: ca-volume
              mountPath: "/etc/ssl/certs/db-ca"
              readOnly: true
          envFrom:
            - secretRef:
                name: backend-secrets
          env:
            - name: FLASK_ENV
              value: production
            # 2. On indique au code Python où se trouve le fichier
            - name: DB_CA_PATH
              value: "/etc/ssl/certs/db-ca/ca.pem"
      # 3. On définit le volume lié au secret
      volumes:
        - name: ca-volume
          secret:
            secretName: db-ca-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer
